/**
 * QScan PDF Report Generator
 * Generates a comprehensive branded PDF report from scan results.
 */
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const COLORS = {
  primary: [15, 23, 42],       // Dark background
  teal: [15, 253, 209],        // Accent
  red: [255, 59, 92],
  orange: [255, 167, 38],
  green: [15, 253, 161],
  white: [226, 232, 240],
  muted: [148, 163, 184],
  darkCard: [30, 41, 59],
};

export function generatePDFReport(cbom, scanId, hndlData) {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = 0;

  // ── Helper: Add a new page if needed ──
  const checkPage = (needed = 30) => {
    if (y + needed > 270) {
      doc.addPage();
      y = 20;
    }
  };

  // ── Page 1: Cover ──
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 297, "F");

  // Header bar
  doc.setFillColor(...COLORS.teal);
  doc.rect(0, 0, pageWidth, 4, "F");

  // Title
  doc.setTextColor(...COLORS.teal);
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.text("QScan", margin, 45);

  doc.setFontSize(14);
  doc.setTextColor(...COLORS.white);
  doc.text("Quantum Readiness Assessment Report", margin, 55);

  // Divider
  doc.setDrawColor(...COLORS.teal);
  doc.setLineWidth(0.5);
  doc.line(margin, 62, pageWidth - margin, 62);

  // Scan metadata
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  const domain = cbom?.metadata?.organization_domain || "Unknown";
  const scanDate = cbom?.metadata?.generated_at
    ? new Date(cbom.metadata.generated_at).toLocaleString()
    : new Date().toLocaleString();

  doc.text(`Target: ${domain}`, margin, 72);
  doc.text(`Scan ID: ${scanId}`, margin, 79);
  doc.text(`Generated: ${scanDate}`, margin, 86);
  doc.text(`Tool: QScan v1.0.0`, margin, 93);

  // Summary box
  y = 110;
  doc.setFillColor(...COLORS.darkCard);
  doc.roundedRect(margin, y, pageWidth - 2 * margin, 50, 3, 3, "F");

  doc.setFontSize(12);
  doc.setTextColor(...COLORS.teal);
  doc.text("Executive Summary", margin + 5, y + 10);

  doc.setFontSize(10);
  doc.setTextColor(...COLORS.white);

  const summary = cbom?.summary || {};
  const totalAssets = summary.total_assets || 0;
  const avgRisk = summary.average_risk_score || 0;
  const readiness = summary.overall_quantum_readiness || "UNKNOWN";
  const critical = summary.risk_distribution?.CRITICAL || 0;
  const high = summary.risk_distribution?.HIGH || 0;

  doc.text(`Total Assets Scanned: ${totalAssets}`, margin + 5, y + 20);
  doc.text(`Average Risk Score: ${avgRisk.toFixed(1)} / 100`, margin + 5, y + 27);
  doc.text(`Overall Quantum Readiness: ${readiness}`, margin + 5, y + 34);
  doc.text(`Critical: ${critical}  |  High: ${high}  |  Forward Secrecy: ${summary.forward_secrecy_adoption || "N/A"}`, margin + 5, y + 41);

  // ── HNDL Risk Assessment ──
  if (hndlData) {
    y = 175;
    doc.setFillColor(...COLORS.darkCard);
    doc.roundedRect(margin, y, pageWidth - 2 * margin, 55, 3, 3, "F");

    doc.setFontSize(12);
    doc.setTextColor(...COLORS.teal);
    doc.text("HNDL Mosca Inequality Risk Assessment", margin + 5, y + 10);

    const breachColor = hndlData.mosca_breach ? COLORS.red : COLORS.green;
    doc.setTextColor(...breachColor);
    doc.setFontSize(11);
    doc.text(
      hndlData.mosca_breach ? "BREACH WINDOW OPEN" : "SAFE",
      margin + 5, y + 20
    );

    doc.setFontSize(10);
    doc.setTextColor(...COLORS.white);
    doc.text(
      `Mosca Inequality: X(${hndlData.migration_years_x}) + Y(${hndlData.data_life_years_y}) = ${hndlData.mosca_sum}  vs  Z(${hndlData.crqc_timeline_years})`,
      margin + 5, y + 28
    );
    doc.text(`Algorithm: ${hndlData.algorithm_assessed}  |  Urgency: ${hndlData.urgency}`, margin + 5, y + 35);
    doc.text(`Sessions at Risk: ${hndlData.sessions_at_risk?.toLocaleString()}  |  Data at Risk: ${hndlData.data_at_risk_gb} GB`, margin + 5, y + 42);

    doc.setTextColor(...COLORS.muted);
    doc.setFontSize(9);
    doc.text(`Source: ${hndlData.crqc_source}`, margin + 5, y + 49);
  }

  // Footer
  doc.setTextColor(...COLORS.muted);
  doc.setFontSize(8);
  doc.text("Generated by QScan — Quantum Readiness Assessment Platform", margin, 285);
  doc.text("Punjab National Bank Cybersecurity Hackathon — Team CacheMe", pageWidth - margin, 285, { align: "right" });

  // ── Page 2: Crypto Assets Table ──
  doc.addPage();
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 297, "F");
  doc.setFillColor(...COLORS.teal);
  doc.rect(0, 0, pageWidth, 3, "F");

  y = 20;
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.teal);
  doc.text("Cryptographic Asset Inventory", margin, y);

  y += 10;

  const assets = cbom?.crypto_assets || [];
  if (assets.length > 0) {
    const tableData = assets.map(asset => [
      `${asset.host}:${asset.port}`,
      asset.tls_configuration?.protocol_version || asset.tls_version || "—",
      (asset.tls_configuration?.negotiated_cipher || asset.cipher_suite || "—").slice(0, 28),
      asset.quantum_assessment?.pqc_status || asset.pqcClassification?.status || "—",
      asset.quantum_assessment?.risk_score?.toFixed(1) || asset.riskScore?.toFixed(1) || "—",
      asset.quantum_assessment?.risk_level || asset.riskLevel?.level || "—",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Asset", "TLS", "Cipher Suite", "PQC Status", "Risk", "Level"]],
      body: tableData,
      theme: "grid",
      styles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontSize: 8,
        cellPadding: 3,
        lineColor: [50, 60, 80],
        lineWidth: 0.3,
      },
      headStyles: {
        fillColor: [20, 30, 50],
        textColor: COLORS.teal,
        fontStyle: "bold",
        fontSize: 9,
      },
      alternateRowStyles: {
        fillColor: [20, 28, 45],
      },
      margin: { left: margin, right: margin },
    });

    y = doc.lastAutoTable.finalY + 15;
  }

  // ── Recommendations Table ──
  checkPage(50);
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.teal);
  doc.text("PQC Migration Recommendations", margin, y);
  y += 10;

  const allRecs = [];
  for (const asset of assets) {
    for (const rec of (asset.recommendations || [])) {
      allRecs.push([
        asset.host,
        rec.component,
        rec.current,
        rec.recommended,
        rec.priority,
        rec.hybrid_option || "—",
      ]);
    }
  }

  if (allRecs.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [["Host", "Component", "Current", "Recommended", "Priority", "Hybrid Option"]],
      body: allRecs,
      theme: "grid",
      styles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontSize: 7.5,
        cellPadding: 2.5,
        lineColor: [50, 60, 80],
        lineWidth: 0.3,
      },
      headStyles: {
        fillColor: [20, 30, 50],
        textColor: COLORS.teal,
        fontStyle: "bold",
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [20, 28, 45],
      },
      margin: { left: margin, right: margin },
      columnStyles: {
        0: { cellWidth: 30 },
        3: { cellWidth: 32 },
      },
    });

    y = doc.lastAutoTable.finalY + 15;
  }

  // ── Risk Matrix ──
  const riskMatrix = cbom?.risk_matrix || [];
  if (riskMatrix.length > 0) {
    checkPage(50);
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.teal);
    doc.text("Risk Matrix", margin, y);
    y += 10;

    const riskData = riskMatrix.map(r => [
      r.host,
      String(r.port),
      r.risk_score?.toFixed(1) || "—",
      r.risk_level || "—",
      r.pqc_status || "—",
      r.migration_deadline || "—",
      r.urgency || "—",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Host", "Port", "Risk Score", "Level", "PQC Status", "Deadline", "Urgency"]],
      body: riskData,
      theme: "grid",
      styles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontSize: 8,
        cellPadding: 2.5,
        lineColor: [50, 60, 80],
        lineWidth: 0.3,
      },
      headStyles: {
        fillColor: [20, 30, 50],
        textColor: COLORS.teal,
        fontStyle: "bold",
        fontSize: 8.5,
      },
      alternateRowStyles: {
        fillColor: [20, 28, 45],
      },
      margin: { left: margin, right: margin },
    });
  }

  // ── Footer on last page ──
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, 290, { align: "right" });
    if (i > 1) {
      doc.text("QScan — Quantum Readiness Assessment Report", margin, 290);
    }
  }

  // Save
  const filename = `QScan_Report_${domain.replace(/\./g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);

  return filename;
}


/**
 * Download raw CBOM as JSON
 */
export function downloadCBOM(cbom) {
  const domain = cbom?.metadata?.organization_domain || "scan";
  const blob = new Blob([JSON.stringify(cbom, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `QScan_CBOM_${domain.replace(/\./g, "_")}_${new Date().toISOString().slice(0, 10)}.json`;
  a.click();
  URL.revokeObjectURL(url);
}
